language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -e .

script: pytest

jobs:
  include:
    - stage: Bandit Tests
      python: "3.6"
      install: pip install -r dev-requirements.txt
      script: bandit -t terraguard