language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install -e .

jobs:
  include:
    - script: pytest
    - stage: Bandit Tests
      script: bandit -t terraguard